
package com.yoho.yhorder.invoice.webservice;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-24T18:33:27.733+08:00
 * Generated source version: 3.1.6
 * 
 */

public  interface ClientService {

    String fpkj(String wsdlUrl);
}
