package com.yoho.yhorder.invoice.webservice;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.1.6
 * 2016-05-24T18:33:27.847+08:00
 * Generated source version: 3.1.6
 * 
 */
@WebService(targetNamespace = "http://dsqzjk.dzfpqz", name = "DZFPServicePortType")
@XmlSeeAlso({ObjectFactory.class})
public interface DZFPServicePortType {

    @WebMethod
    @RequestWrapper(localName = "doService", targetNamespace = "http://dsqzjk.dzfpqz", className = "com.yoho.yhorder.invoice.webservice.DoService")
    @ResponseWrapper(localName = "doServiceResponse", targetNamespace = "http://dsqzjk.dzfpqz", className = "com.yoho.yhorder.invoice.webservice.DoServiceResponse")
    @WebResult(name = "out", targetNamespace = "http://dsqzjk.dzfpqz")
    String doService(
            @WebParam(name = "in0", targetNamespace = "http://dsqzjk.dzfpqz")
            String in0
    );
}
