package com.yoho.yhorder.dal;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.yoho.yhorder.dal.model.OrdersPayRefund;

public interface OrdersPayRefundMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_pay_refund
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_pay_refund
     *
     * @mbggenerated
     */
    int insert(OrdersPayRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_pay_refund
     *
     * @mbggenerated
     */
    int insertSelective(OrdersPayRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_pay_refund
     *
     * @mbggenerated
     */
    OrdersPayRefund selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_pay_refund
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(OrdersPayRefund record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table orders_pay_refund
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(OrdersPayRefund record);
    
    //根据订单号获取退款记录
    List<OrdersPayRefund> selectByOrderCode(long orderCode);
    
    //查看部分退款记录是否存在
    OrdersPayRefund selectByRefundOrderCode(@Param("refundOrderCode") String refundOrderCode);
}