package com.yoho.yhorder.dal;

import com.yoho.service.model.order.response.PaymentData;

public interface PaymentDataMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_data
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_data
     *
     * @mbggenerated
     */
    int insert(PaymentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_data
     *
     * @mbggenerated
     */
    int insertSelective(PaymentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_data
     *
     * @mbggenerated
     */
    PaymentData selectByPrimaryKey(Integer id);

    PaymentData selectByOrderCode(Long orderCode);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(PaymentData record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table payment_data
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(PaymentData record);
}