package com.yoho.yhorder.dal.model;

import java.math.BigDecimal;

public class OrdersPayRefund {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.id
     *
     * @mbggenerated
     */
    private Integer id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.refund_order_code
     *
     * @mbggenerated
     */
    private Long refundOrderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.order_code
     *
     * @mbggenerated
     */
    private Long orderCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.payment
     *
     * @mbggenerated
     */
    private Byte payment;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.serial_no
     *
     * @mbggenerated
     */
    private String serialNo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.amount
     *
     * @mbggenerated
     */
    private BigDecimal amount;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.status
     *
     * @mbggenerated
     */
    private Byte status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.refund_status
     *
     * @mbggenerated
     */
    private String refundStatus;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.create_time
     *
     * @mbggenerated
     */
    private Integer createTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column orders_pay_refund.update_time
     *
     * @mbggenerated
     */
    private Integer updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.id
     *
     * @return the value of orders_pay_refund.id
     *
     * @mbggenerated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.id
     *
     * @param id the value for orders_pay_refund.id
     *
     * @mbggenerated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.refund_order_code
     *
     * @return the value of orders_pay_refund.refund_order_code
     *
     * @mbggenerated
     */
    public Long getRefundOrderCode() {
        return refundOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.refund_order_code
     *
     * @param refundOrderCode the value for orders_pay_refund.refund_order_code
     *
     * @mbggenerated
     */
    public void setRefundOrderCode(Long refundOrderCode) {
        this.refundOrderCode = refundOrderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.order_code
     *
     * @return the value of orders_pay_refund.order_code
     *
     * @mbggenerated
     */
    public Long getOrderCode() {
        return orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.order_code
     *
     * @param orderCode the value for orders_pay_refund.order_code
     *
     * @mbggenerated
     */
    public void setOrderCode(Long orderCode) {
        this.orderCode = orderCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.payment
     *
     * @return the value of orders_pay_refund.payment
     *
     * @mbggenerated
     */
    public Byte getPayment() {
        return payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.payment
     *
     * @param payment the value for orders_pay_refund.payment
     *
     * @mbggenerated
     */
    public void setPayment(Byte payment) {
        this.payment = payment;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.serial_no
     *
     * @return the value of orders_pay_refund.serial_no
     *
     * @mbggenerated
     */
    public String getSerialNo() {
        return serialNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.serial_no
     *
     * @param serialNo the value for orders_pay_refund.serial_no
     *
     * @mbggenerated
     */
    public void setSerialNo(String serialNo) {
        this.serialNo = serialNo == null ? null : serialNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.amount
     *
     * @return the value of orders_pay_refund.amount
     *
     * @mbggenerated
     */
    public BigDecimal getAmount() {
        return amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.amount
     *
     * @param amount the value for orders_pay_refund.amount
     *
     * @mbggenerated
     */
    public void setAmount(BigDecimal amount) {
        this.amount = amount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.status
     *
     * @return the value of orders_pay_refund.status
     *
     * @mbggenerated
     */
    public Byte getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.status
     *
     * @param status the value for orders_pay_refund.status
     *
     * @mbggenerated
     */
    public void setStatus(Byte status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.refund_status
     *
     * @return the value of orders_pay_refund.refund_status
     *
     * @mbggenerated
     */
    public String getRefundStatus() {
        return refundStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.refund_status
     *
     * @param refundStatus the value for orders_pay_refund.refund_status
     *
     * @mbggenerated
     */
    public void setRefundStatus(String refundStatus) {
        this.refundStatus = refundStatus == null ? null : refundStatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.create_time
     *
     * @return the value of orders_pay_refund.create_time
     *
     * @mbggenerated
     */
    public Integer getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.create_time
     *
     * @param createTime the value for orders_pay_refund.create_time
     *
     * @mbggenerated
     */
    public void setCreateTime(Integer createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column orders_pay_refund.update_time
     *
     * @return the value of orders_pay_refund.update_time
     *
     * @mbggenerated
     */
    public Integer getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column orders_pay_refund.update_time
     *
     * @param updateTime the value for orders_pay_refund.update_time
     *
     * @mbggenerated
     */
    public void setUpdateTime(Integer updateTime) {
        this.updateTime = updateTime;
    }
}